import { useEffect, useMemo, useState } from 'react';
import { loadModel } from './model/loadModel';
import { run } from './model/inference';
import type { Model, TokenTrace, Trace } from './model/types';
import { formulas } from './formulas';
import Comparison from './components/Comparison';
import { tokenize } from './model/tokenizer';
import { ChevronLeft, ChevronRight, Delete, Microscope, Pause, Play, RotateCcw, ScanSearch, Sparkles, Trash2 } from 'lucide-react';

const examples = ['The red robot picked up the blue key. It walked toward the door.', 'The dog dropped the ball. It rolled under the table.', 'The dog chased the ball. It barked loudly.', 'Alice handed the map to Bob. He thanked Alice.'];
const wordGroups = [
  ['Pronouns', ['i', 'it', 'he', 'she']],
  ['Names', ['alice', 'bob', 'maya', 'liam', 'noah', 'emma', 'olivia']],
  ['Nouns', ['robot', 'android', 'dog', 'cat', 'fox', 'astronaut', 'key', 'ball', 'book', 'map', 'coin', 'letter', 'camera', 'box', 'door', 'table', 'desk', 'garden', 'room', 'moon', 'telescope']],
  ['Verbs', ['picked', 'walked', 'dropped', 'rolled', 'chased', 'barked', 'handed', 'gave', 'thanked', 'placed', 'opened', 'carried', 'found', 'held', 'moved', 'saw', 'looked', 'read', 'closed']],
  ['Descriptors', ['red', 'blue', 'green', 'yellow', 'small', 'big', 'loudly', 'carefully']],
  ['Connectors', ['the', 'a', 'an', 'and', 'to', 'up', 'toward', 'under', 'on', 'in', 'with', 'because', 'so', 'but', 'then', 'before', 'after']],
  ['Punctuation', ['.', ',']],
] as const;
const fmt = (v: number) => v.toFixed(3);
const Vector = ({ values, name }: { values: Float32Array; name: string }) => { const shown = [...values]; const max = Math.max(...shown.map(Math.abs), .0001); return <div className="vector visual-vector" aria-label={name}>{shown.map((v, i) => <span key={i} title={`${name}[${i}] = ${v}`} style={{ '--height': `${Math.max(8, Math.abs(v) / max * 100)}%`, '--sign': v < 0 ? '#e38aa7' : '#65d4c3' } as React.CSSProperties}><i/ ><small>{i}</small><b>{fmt(v)}</b></span>)}<em>all {values.length}</em></div>; };
const Matrix = ({ values, rows, cols, name }: { values: Float32Array; rows: number; cols: number; name: string }) => { const visibleRows = Math.min(rows, 6), visibleCols = Math.min(cols, 8); const max = Math.max(...[...values].map(Math.abs), .0001); return <figure className="matrix-plot"><div className="matrix heatmap heatmap-8" aria-label={name}>{Array.from({ length: visibleRows * visibleCols }, (_, i) => { const value = values[Math.floor(i / visibleCols) * cols + i % visibleCols]; return <span key={i} title={`${name}[${Math.floor(i / visibleCols)},${i % visibleCols}] = ${value}`} style={{ opacity: .18 + Math.abs(value) / max * .82, background: value < 0 ? '#c96d90' : '#42b9ad' }}>{fmt(value)}</span>; })}</div><figcaption><i/> negative <i/> positive · {visibleRows}×{visibleCols} view</figcaption></figure>; };
const FlowOverview = ({ token, data, kind }: { token: TokenTrace; data: TokenTrace['layers'][number]; kind?: string; eventIndex: number }) => { const paths = ['M98 88 H237', 'M323 88 H372', 'M458 88 H602', 'M688 88 H742', 'M828 88 H887', 'M415 131 C415 165 645 165 645 131']; const pathFor: Record<string, number> = { embedding_lookup: 0, q_projection: 1, k_projection: 1, v_projection: 1, feature_map_q: 2, feature_map_k: 2, outer_product: 5, state_s_update: 5, state_z_update: 5, state_read_numerator: 3, state_read_denominator: 3, context_divide: 3, prediction: 4, reconstructed_influence: 4 }; const activePath = kind ? pathFor[kind] : undefined; return <section className="panel flow-overview"><h2>Live computation map</h2><svg viewBox="0 0 1000 180" role="img" aria-label="Token flows through embedding, Q K V, recurrent state, readout, and prediction"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#75d8ca"/></marker></defs>{paths.map((path, i) => <g key={path}><path className={`flow-path ${i === 5 ? 'secondary' : ''} ${i === activePath ? 'active-flow' : ''}`} d={path}/>{i === activePath && <circle className={`tensor-packet packet-${i}`} r="5"><animateMotion dur="1.35s" repeatCount="indefinite" path={path}/></circle>}</g>)}{[['TOKEN',token.token,55],['EMBED','32D',280],['Q / K / V','16 / 16 / 32',415],['S + Z','memory',645],['READ','context',785],['PREDICT','antecedent',930]].map(([label,value,x]) => <g key={String(label)} transform={`translate(${x},88)`}><circle r="43"/><text y="-4">{label}</text><text y="15" className="flow-value">{value}</text></g>)}</svg><div className="flow-caption"><span>Q strength <b style={{ width: `${Math.min(100, Math.abs(data.q[0]) * 18)}%` }}/></span><span>memory write <b style={{ width: `${Math.min(100, Math.abs(data.contribution[0]) * 30)}%` }}/></span><span>current operation: {kind ?? 'idle'}</span></div></section>; };

export default function App() {
  const [model, setModel] = useState<Model>(); const [error, setError] = useState(''); const [text, setText] = useState(examples[0]); const [trace, setTrace] = useState<Trace>(); const [step, setStep] = useState(0); const [layer, setLayer] = useState(1); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1); const [difference, setDifference] = useState(false); const [microscope, setMicroscope] = useState(false); const [pinnedId, setPinnedId] = useState<string>();
  useEffect(() => { loadModel().then(m => { setModel(m); setTrace(run(m, text)); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (!playing || !trace) return; const timer = window.setInterval(() => setStep(s => s >= trace.events.length - 1 ? (setPlaying(false), s) : s + 1), 550 / speed); return () => clearInterval(timer); }, [playing, trace, speed]);
  useEffect(() => { const keys = (e: KeyboardEvent) => { if (e.key === 'ArrowRight') setStep(s => Math.min((trace?.events.length ?? 1) - 1, s + 1)); if (e.key === 'ArrowLeft') setStep(s => Math.max(0, s - 1)); if (e.key === ' ') { e.preventDefault(); setPlaying(value => !value); } if (e.key.toLowerCase() === 'r') setStep(0); }; addEventListener('keydown', keys); return () => removeEventListener('keydown', keys); }, [trace]);
  const event = trace?.events[step]; const tokenIndex = event?.tokenIndex ?? 0; const token = trace?.tokens[tokenIndex]; const activeLayer = Math.min(layer, (token?.layers.length ?? 1) - 1); const data = token?.layers[activeLayer];
  const inspected = trace && (pinnedId ? trace.artifacts[pinnedId] : event?.outputIds[0] ? trace.artifacts[event.outputIds[0]] : undefined);
  const prediction = useMemo(() => token?.prediction && [...token.prediction.probabilities].map((p, i) => ({ label: token.prediction!.labels[i], p })).sort((a,b) => b.p-a.p).slice(0, 4), [token]);
  const requestedTokens = tokenize(text); const oovCount = requestedTokens.filter(word => !model?.vocab.includes(word)).length;
  const execute = () => { if (!model) return; const next = run(model, text); setTrace(next); setStep(0); setPlaying(false); };
  if (error) return <main className="error">Model loading error: {error}</main>; if (!model || !trace || !data) return <main className="loading">Loading the tiny trained linear-attention model…</main>;
  const jumpPronoun = () => { const i = trace.events.findIndex(e => trace.tokens[e.tokenIndex ?? -1]?.prediction); if (i >= 0) setStep(i); };
  const renderTokens = (tokens: string[]) => tokens.join(' ').replaceAll(' .', '.').replaceAll(' ,', ',');
  const addToken = (word: string) => setText(current => renderTokens([...tokenize(current), word]));
  const removeToken = () => setText(current => renderTokens(tokenize(current).slice(0, -1)));
  return <main>
    <header><div><p className="eyebrow">LINEAR ATTENTION / TRACE LAB</p><h1>Memory, made visible.</h1></div><div className="legend"><span className="learned">● Learned</span><span className="computed">● Computed</span><span className="reconstructed">● Reconstructed</span></div></header>
    <section className="input panel"><div className="sentence-builder" aria-label="Selected input words">{requestedTokens.length ? requestedTokens.map((word, index) => <span key={`${word}-${index}`}>{word}</span>) : <small>Choose words below</small>}</div><button className="run" onClick={execute} title="Run trace" aria-label="Run trace"><Play size={15}/><span>Run</span></button><button className="icon-button" onClick={removeToken} disabled={!requestedTokens.length} title="Remove last word" aria-label="Remove last word"><Delete size={15}/></button><button className="icon-button" onClick={() => setText('')} disabled={!requestedTokens.length} title="Clear sentence" aria-label="Clear sentence"><Trash2 size={15}/></button><select aria-label="Examples" onChange={e => { setText(e.target.value); }} value={examples.includes(text) ? text : ''}><option value="" disabled>Examples</option>{examples.concat('I saw an astronaut in the moon with a telescope.').map(x => <option key={x}>{x}</option>)}</select><small>Word bank only · max {model.config.maxLength} tokens</small><div className="word-bank" aria-label="Supported word bank">{wordGroups.map(([group, words]) => <div className="word-group" key={group}><label>{group}</label><div>{words.filter(word => model.vocab.includes(word)).map(word => <button key={word} onClick={() => addToken(word)}>{word}</button>)}</div></div>)}</div>{requestedTokens.length > model.config.maxLength && <p className="input-warning">Only the first {model.config.maxLength} tokens can be traced.</p>}</section>
    <section className="timeline panel" aria-label="Token timeline">{trace.tokens.map((item, i) => <button key={`${item.token}-${i}`} onClick={() => setStep(trace.events.findIndex(e => e.tokenIndex === i))} className={i === tokenIndex ? 'current' : i < tokenIndex ? 'processed' : ''}>{item.token}<small>#{i}{item.oov && ' · OOV'}</small></button>)}</section>
    <nav className="controls panel"><button className="icon-button" onClick={() => setStep(Math.max(0, step - 1))} title="Previous operation" aria-label="Previous operation"><ChevronLeft/></button><button className="icon-button primary" onClick={() => setPlaying(!playing)} title={playing ? 'Pause' : 'Play'} aria-label={playing ? 'Pause' : 'Play'}>{playing ? <Pause/> : <Play/>}</button><button className="icon-button" onClick={() => setStep(Math.min(trace.events.length - 1, step + 1))} title="Next operation" aria-label="Next operation"><ChevronRight/></button><button className="icon-button" onClick={jumpPronoun} title="Jump to pronoun" aria-label="Jump to pronoun"><ScanSearch/></button><button className="icon-button" onClick={() => setStep(0)} title="Restart" aria-label="Restart"><RotateCcw/></button><button className={`icon-button ${microscope ? 'active' : ''}`} onClick={() => setMicroscope(!microscope)} title="Toggle microscope mode" aria-label="Toggle microscope mode"><Microscope/></button><label className="speed" title="Playback speed"><Sparkles size={13}/><select aria-label="Playback speed" value={speed} onChange={e => setSpeed(+e.target.value)}><option value="0.5">0.5×</option><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label><span>Step {step + 1} / {trace.events.length} · {event?.shortLabel}</span></nav>
    <section className="layers"><button className={activeLayer === 0 ? 'selected' : ''} onClick={() => setLayer(0)}>Layer 1</button><span>Embedding → Layer 1 → Layer 2 → Task head</span><button className={activeLayer === 1 ? 'selected' : ''} onClick={() => setLayer(1)}>Layer 2</button></section>
    <FlowOverview token={token!} data={data} kind={event?.kind} eventIndex={step}/>
    <div className="workspace">
      <section className="panel embed"><h2>Token / Embed <b>Learned</b></h2><strong>{token?.token} <small>id {token?.id}</small></strong><Vector name="embedding" values={Float32Array.from(model.embeddings[token!.id])}/><p>Lookup row → layer input</p></section>
      <section className="panel qkv"><h2>Q / K / V laboratory <b>Computed</b></h2><div className="lanes"><div><label>Q = xWq + bq</label><Vector name="Q" values={data.q}/><label>φ(Q)</label><Vector name="phi Q" values={data.qphi}/></div><div><label>K = xWk + bk</label><Vector name="K" values={data.k}/><label>φ(K)</label><Vector name="phi K" values={data.kphi}/></div><div><label>V = xWv + bv</label><Vector name="V" values={data.v}/></div></div></section>
      <section className="panel contribution"><h2>Contribution <b>Computed</b></h2><code>C = φ(K) ⊗ V</code><Matrix name="contribution" values={data.contribution} rows={model.config.dFeature} cols={model.config.dModel}/>{microscope && <p>C[0,0] = φ(K)[0] × V[0] = {fmt(data.kphi[0])} × {fmt(data.v[0])} = {fmt(data.contribution[0])}</p>}</section>
      <section className="panel readout"><h2>Read before write</h2><code>N = φ(Q)ᵀSₜ₋₁</code><Vector name="numerator" values={data.numerator}/><code>D = φ(Q)ᵀZₜ₋₁ + ε = {fmt(data.denominator)}</code><Vector name="context" values={data.context}/></section>
      <section className="panel state"><h2>State memory S / Z <b>Computed</b></h2><button className="minor" onClick={() => setDifference(!difference)}>{difference ? 'Combined state' : 'Difference view ΔS'}</button><div className="state-grid"><div><label>S before</label><Matrix name="S before" values={data.beforeS} rows={model.config.dFeature} cols={model.config.dModel}/></div><div className="plus">＋</div><div><label>C</label><Matrix name="C" values={data.contribution} rows={model.config.dFeature} cols={model.config.dModel}/></div><div className="equals">＝</div><div><label>{difference ? 'ΔS = C' : 'S after'}</label><Matrix name="S after" values={difference ? data.contribution : data.afterS} rows={model.config.dFeature} cols={model.config.dModel}/></div></div><label>Z before → after</label><Vector name="Z" values={data.afterZ}/><p>History: S0 → … → S{tokenIndex} ({token?.token})</p></section>
      <section className="panel prediction"><h2>Prediction / influence</h2>{prediction ? <><p>{token.prediction!.fullSentence ? 'Full-sentence resolver' : 'Causal resolver'} prediction for “{token?.token}”</p>{prediction.map(row => <div className="score" key={row.label}><span>{row.label}</span><i style={{ width: `${row.p * 100}%` }}/><strong>{(row.p * 100).toFixed(1)}%</strong></div>)}<div className="influence">{token.prediction!.influence.map((value, i) => <button key={i} title={`Reconstructed φ(Q)·φ(K): ${value.toFixed(4)}`} style={{ height: `${Math.max(8, value * 170)}px` }} onClick={() => setStep(trace.events.findIndex(e => e.tokenIndex === i))}><small>{trace.tokens[i].token}</small></button>)}</div><p className="reconstructed">{token.prediction!.fullSentence ? 'Uses a second reverse linear pass after the sentence ends; the bars above may include later entities. The chart remains forward causal influence.' : 'Reconstructed kernel influence — forward inference uses S/Z, not this history.'}</p></> : <p>Prediction activates on supported pronouns.</p>}</section>
    </div>
    <section className="panel inspector"><h2>Inspector / provenance</h2>{inspected ? <><strong>{inspected.label} <b className={inspected.source}>{inspected.source}</b></strong><p>shape [{inspected.shape.join(' × ') || 'scalar'}] · token {inspected.tokenIndex ?? '—'} · layer {(inspected.layerIndex ?? -1) + 1 || '—'}</p><Vector name={inspected.label} values={typeof inspected.values === 'number' ? new Float32Array([inspected.values]) : inspected.values}/><p>Parents</p><div className="parents">{(inspected.parentIds ?? []).length ? inspected.parentIds!.map(id => <button key={id} onClick={() => setPinnedId(id)}>{trace.artifacts[id]?.label ?? id}</button>) : 'No prior tensor: learned parameter or trace root.'}</div><button className="minor" onClick={() => setPinnedId(undefined)}>Follow active operation</button></> : <p>Select an operation to inspect its output and lineage.</p>}<p className="event-links">Active inputs: {event?.inputIds.map(id => <button key={id} onClick={() => setPinnedId(id)}>{trace.artifacts[id]?.label ?? id}</button>)}</p></section>
    <Comparison/><footer className="formula"><strong>{formulas[event?.formulaKey ?? 'tokenize'].math}</strong><small>{formulas[event?.formulaKey ?? 'tokenize'].detail}</small></footer>
  </main>;
}
